version: '3'

services:
  trello-backup:
    build:
      context: .
    volumes:
      - ./resources/:/usr/src/output
    env_file:
      - trello-backup.env

  backup-maker:
    build:
      context: .
    volumes:
      - ./resources/:/usr/src/output
    env_file:
      - trello-backup.env
    command: bash -c "./prepare-config.sh && ./make-backup.sh"
